import turtle


def sierpinskicarpet(degree, length):
    if degree > 0:
        sierpinskicarpet(degree - 1, length / 3)
        sierpinskicarpet(degree - 1, length / 3)
        sierpinskicarpet(degree - 1, length / 3)
        turtle.back(length)
        turtle.right(90)
        turtle.forward(length / 3)
        turtle.left(90)
        sierpinskicarpet(degree - 1, length / 3)
        turtle.forward(length / 3)
        sierpinskicarpet(degree - 1, length / 3)
        turtle.back(length)
        turtle.right(90)
        turtle.forward(length / 3)
        turtle.left(90)
        sierpinskicarpet(degree - 1, length / 3)
        sierpinskicarpet(degree - 1, length / 3)
        sierpinskicarpet(degree - 1, length / 3)
        turtle.left(90)
        turtle.forward(length * 2 / 3)
        turtle.right(90)
    else:
        turtle.begin_fill()
        turtle.forward(length)
        turtle.right(90)
        turtle.forward(length)
        turtle.right(90)
        turtle.forward(length)
        turtle.right(90)
        turtle.forward(length)
        turtle.end_fill()
        turtle.right(90)
        turtle.forward(length)


def sierpinskicarpetoptimal(degree, length):
    if degree > 0:
        # turtle.begin_fill()
        # turtle.forward(length)
        # turtle.right(90)
        # turtle.forward(length)
        # turtle.right(90)
        # turtle.forward(length)
        # turtle.right(90)
        # turtle.forward(length)
        # turtle.right(90)
        # turtle.end_fill()
        sierpinskicarpetoptimal(degree - 1, length / 3)
        sierpinskicarpetoptimal(degree - 1, length / 3)
        sierpinskicarpetoptimal(degree - 1, length / 3)
        turtle.back(length)
        turtle.right(90)
        turtle.forward(length / 3)
        turtle.left(90)
        sierpinskicarpetoptimal(degree - 1, length / 3)
        turtle.fillcolor('white')
        turtle.begin_fill()
        turtle.forward(length/3)
        turtle.right(90)
        turtle.forward(length/3)
        turtle.right(90)
        turtle.forward(length/3)
        turtle.right(90)
        turtle.forward(length/3)
        turtle.right(90)
        turtle.end_fill()
        turtle.fillcolor('black')
        turtle.forward(length/3)
        sierpinskicarpetoptimal(degree - 1, length / 3)
        turtle.back(length)
        turtle.right(90)
        turtle.forward(length / 3)
        turtle.left(90)
        sierpinskicarpetoptimal(degree - 1, length / 3)
        sierpinskicarpetoptimal(degree - 1, length / 3)
        sierpinskicarpetoptimal(degree - 1, length / 3)
        turtle.left(90)
        turtle.forward(length * 2 / 3)
        turtle.right(90)
    else:
        turtle.forward(length)


turtle.speed(0)
turtle.begin_fill()
turtle.forward(300)
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.end_fill()
sierpinskicarpetoptimal(4, 300)
turtle.done()
